### ISSUE TITLE
create_model gives parse error

### ISSUE THREAD

**Issue by Arthur-Zestco** [JBGruber/rollama#11] opened 2024-05-15 20:23 UTC
I can make queries to my local Ollama server with no issues, but when I try to use a modelfile to create a new model I get a parse error...
```
> modelfile <- "FROM llama2:text\nSYSTEM You are mario from Super Mario Bros."
> rollama::create_model("mario", modelfile)
Error: parse error: trailing garbage
          parameter\", or \"message\""}{"error":"invalid model referen
                     (right here) ------^
```

It does appear to create a model

```
### before

> rollama::list_models()[c("model", "digest","modified_at")]
# A tibble: 1 × 3
  model               digest                                                           modified_at                        
  <chr>               <chr>                                                            <chr>                              
1 llama2:text         53b394a404fd4d4e14083f9b2d82f03fc787e9330fcc3885261eb3d5f14a3ef1 2024-03-15T19:38:18.597182578Z     

### after

> rollama::list_models()[c("model", "digest","modified_at")]
# A tibble: 2 × 3
  model               digest                                                           modified_at                        
  <chr>               <chr>                                                            <chr>                              
1 mario:latest        7b554bbaa2026e20f99ce19d6029240e56398a606919dd86411e0f32a798e3a8 2024-05-15T20:49:42.814356399+01:00
2 llama2:text         53b394a404fd4d4e14083f9b2d82f03fc787e9330fcc3885261eb3d5f14a3ef1 2024-03-15T19:38:18.597182578Z     
```

And the Ollama server console reports no issues

```
[GIN] 2024/05/15 - 20:49:42 | 200 |  184.479959ms |       127.0.0.1 | POST     "/api/create"
```

and the model responds

```
rollama::query("Who is your brother?","mario")
✔ mario is thinking ⠴ [8.9s]

── Answer from mario ─────────────

nobody knows who he is.
> 
```

so it's not your biggest issue, but it is somewhat disconcerting for a new rollama user

```
> version
platform       aarch64-apple-darwin23.4.0  
[...]
version.string R version 4.4.0 (2024-04-24)
nickname       Puppy Cup                   
> getNamespaceVersion("rollama")
version 
"0.1.0"
```

Any suggestions?

**Comment by JBGruber** [comment] 2024-05-25 07:58
I believe this is the same issue as #14. Essentially the parse error is occuring while parsing the progress status from the API. Ollama then conitnues creating the model, but the status output in R crashes. It should be fixed already in the development version (I can't reproduce the error). But thank you for the detailed issue report!

**Closed by JBGruber** 2024-05-25 07:58 UTC
