### ISSUE TITLE
Ollama now supports embedding models

### ISSUE THREAD

**Issue by kasperwelbers** [JBGruber/rollama#5] opened 2024-03-15 08:59 UTC
Ollama [added support for embedding models like BERT](https://github.com/ollama/ollama/issues/327). This is much faster than using a generative model, such as llama2, which is currently the default in embed_text.

Changing this default, and perhaps adding documentation to help people pick good embedding models, could make rollama super useful for all sorts of downsteam tasks in R!

**Comment by JBGruber** [comment] 2024-03-15 10:21
Nice! It didn't work until I updated to v0.1.29. But then `nomic-embed-text` was about 4 times faster than the default `llama2` model in the embedding vignette example (and the f-means of the resulting model was 0.05 better :wink: ).

I think about the best approach for this. Having one default throughout the package is neat, but models meant for embedding are definitly faster and make more sense for a lot of people. I will at least add it to the vignette and the examples.

**Comment by JBGruber** [comment] 2024-03-15 10:47
It's a bit involved, but still okay:

Terminal:

```bash
python3 -m venv env
source env/bin/activate
pip install -U sentence-transformers
```

Python:

```python
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')
```

modelfile.txt:

```
FROM /home/johannes/.cache/huggingface/hub/models--sentence-transformers--paraphrase-MiniLM-L6-v2/blobs/5d716de760acbdc09e79a11e718c5606e0812b6aeb76c6664cba876d174e3ecd
TEMPLATE """{{ .Prompt }}"""
PARAMETER num_ctx 8192
```

R:

```r
library(rollama)
create_model(model = "test", modelfile = "inst/extdata/modelfile.txt")
```

Voila! I assume this could be improved to cut out Python and the venv.

**Comment by kasperwelbers** [comment] 2024-03-15 12:38
Nice, thats really cool!

What is the purpose of Python here? Is this only that it downloads the model? Because then it might also be done with [hfhub](https://cran.r-project.org/web/packages/hfhub/index.html), which seems to be an effort of team posit to get huggingface to R.

**Comment by JBGruber** [comment] 2024-03-15 12:49
That's exactly what I was looking for! For some reason it didn't show up in my searches and I assumed that I've dreamed it :sweat_smile:. Yes, the Python stuff was just for downloading the file. Now all we need is a good heuristic to identify the file Ollama wants.

**Comment by JBGruber** [comment] 2024-03-15 14:50
Ok, I was a bit quick with the post above and couldn't reproduce it with the files downloaded through `hfhub`. Finally, I noticed I had acidetally grabbed the wrong model file.

You need indeed to first follow the steps to [convert the model using `convert-hf-to-gguf.py`](https://github.com/ollama/ollama/blob/main/docs/import.md). And then move the converted bin file to a directory Ollama has access to (in my case inside the container). 

So for now, I would tell people to rely on either [`nomic-embed-text`](https://ollama.com/library/nomic-embed-text) or [`all-minilm`](https://ollama.com/library/all-minilm) and check what might be added in the future.

**Comment by JBGruber** [comment] 2024-12-05 08:52
I'm closing this as completed. Ollama now supports more embedding models itself (https://ollama.com/search?c=embedding) and it is possible to load models (in GGUF format) directly from Hugging Face Hub. I added a vignette that shows how to use it: https://jbgruber.github.io/rollama/articles/hf-gguf.html

If you are eager to use a model not available in the GGUF format yet, ther is still the option to [convert the model using `convert-hf-to-gguf.py`](https://github.com/ollama/ollama/blob/main/docs/import.md) and upload the model to Hugging Face Hub yourself.

**Closed by JBGruber** 2024-12-05 08:52 UTC
